### ISSUE TITLE
Modularise and improve profiling

### ISSUE THREAD

**Issue by MarionBWeinzierl** [ImperialCollegeLondon/pyrealm#141]
As described in #81 , the profiling should be pulled out of the general testing, and in particular the profiling directory, and given its own module. It should then be extended to not only cover the pmodel. We should consider how we want to potentially automate things like creating the call graph etc.

Tasks:
- [x] Make profiling its own module. 
- [x] Extend profiling beyond pmodel.
- [x] Automate call graph creation.
- [x] Consider additional profiling outputs and how to collect them (automatically).
- [x] Adapt and extend the documentation about profiling in the CONTRIBUTING.md file.

**Comment by tztsai** [comment]
I think there could be two solution:

1. The first one would be to create a new folder `profiling` in the root directory and move tests/pmodel/test_profiling.py to profiling/test_pmodel_profiling.py. And we also create profiling scripts for the T Model and the Hygro model, as in the following picture:

<img width="1089" alt="Screenshot 2023-11-28 at 2 09 45 PM" src="https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/15041b0f-3d97-4d40-8ad1-66357c6d256b">

Consequently, we need to update .github/workflows/pyrealm_ci.yaml to run the profiling separately (although this should be addressed later in issue #142), somewhat similar to this:

```yaml

  test:
    ...

    steps:
    - ...

    - name: Profiling
      if: github.ref == 'refs/heads/main'
      run: poetry run pytest profiling/ --profile
```

2. The second one would be to add a `conftest.py` in the tests/ folder with the following content:
<img width="1087" alt="image" src="https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/7e1d876a-6ff3-47d2-b338-ddc412ccfb69">
This will make all classes or functions decorated by `pytest.mark.profiling` skipped during testing unless the argument `--profiling` is provided. An example of marking the tests in tests/pmodel/test_profiling would be
<img width="1180" alt="image" src="https://github.com/ImperialCollegeLondon/pyrealm/assets/34415979/589ea236-175a-4ffb-8ab2-b04785606f56">

Consequently, we also need to update .github/workflows/pyrealm_ci.yaml later, somewhat similar to this:

```yaml

  test:
    ...

    steps:
    - ...

    - name: Run tests with profiling
      if: github.ref == 'refs/heads/main'
      run: poetry run pytest --cov-report xml --profile

   - name: Run tests without profiling
   if: ${{github.ref != 'refs/heads/main'}}
      run: poetry run pytest --cov-report xml
```
This creates two different commands to run conditional on whether the branch is `main`.

The second solution seems more flexible, and we don't have write the same code twice if we want to both test it and profile it. However, it profiles all tests when the argument `--profile` is provided. I don't know if this is the intended behaviour. If we only want to profile certain tests contained in files like `test_profiling.py`, the first solution may be better.
