### ISSUE TITLE
Profiling python version parsed as float

### ISSUE THREAD

**Issue by davidorme** [ImperialCollegeLondon/pyrealm#213]
**Describe the bug**

The `pyrealm_profiling.yaml` contains:

```yaml
    - uses: actions/setup-python@v5
      with:
        python-version: 3.10
```

And that gets parsed as a float, so falls over trying to install `python 3.1`

**To Reproduce**

See here: 
https://github.com/ImperialCollegeLondon/pyrealm/actions/runs/8703804264
